apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-cluster
spec:
  destination:
    name: ''
    namespace: 'eks'
    server: 'https://kubernetes.default.svc'
  source:
    path: capi-cluster/aws-eks
    repoURL: 'https://github.com/smartbenson1/k8s-cluster-api-argocd.git'
    targetRevision: HEAD
    #helm:
     # valueFiles:
       # - values-c1.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
