apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-nginx
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://8CBF9C41B09EF107829877FA6D30AE04.sk1.ap-southeast-2.eks.amazonaws.com'
  source:
    path: app/eks-app
    repoURL: 'https://github.com/smartbenson1/k8s-cluster-api-argocd.git' #Indicate which source repo for fetching the cluster configuration
    targetRevision: HEAD
  project: default #You can give a project name here
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
